### PR TITLE
don't get confused by cabal.project files

### LINKED ISSUE #52: Error: No targets given and there is no package in the current directory
```
$ git clone git@github.com:haskell-works/hw-bits.git
$ cd hw-bits
$ policeman
⚙  curl --silent 'http://hackage.haskell.org/package/hw-bits/hw-bits-0.7.1.0.tar.gz' --output .policeman-evidence/hw-bits-0.7.1.0.tar.gz
⚙  tar -xf .policeman-evidence/hw-bits-0.7.1.0.tar.gz -C .policeman-evidence
⚙  cabal clean
⚙  cabal v2-build '--ghc-options=-fwrite-ide-info' '--ghc-options=-hiedir=.hie' '--verbose=0'
cabal: No targets given and there is no package in the current directory. Use
the target 'all' for all packages in the project or specify packages or
components by name or location. See 'cabal build --help' for more details on
target options.

policeman: callCommand: cabal v2-build '--ghc-options=-fwrite-ide-info' '--ghc-options=-hiedir=.hie' '--verbose=0' (exit 1): failed
```

### PR DESCRIPTION
**Pull request by gelisam**
Fixes #52.

When run from a folder `<my-project>` which contains a cabal.project
file, policeman will fail with the following message:

    cabal: No targets given and there is no package in the current
    directory. [...]

In fact, there is a package in the current directory, which policeman
just created at `<my-project>/.policeman-evidence/<my-project>-<previous-version>`.
Unfortunately, since that newly-created directory is not listed in
`<my-project>/cabal.project`, it is ignored by cabal.

The solution is to create a competing file at
`<my-project>/.policeman-evidence/<my-project>-<previous-version>/cabal.project`.
cabal will find that file first, and since that file does list the
current directory, cabal will accept to build it.

### CODE REVIEW

File: src/Policeman/Hie.hs [hunk 1]
```diff
@@ -21,6 +21,11 @@ createHieFiles :: FilePath -> IO [HieFile]
 createHieFiles projectDir = do
     curDir <- getCurrentDirectory
     setCurrentDirectory projectDir
+
+    -- make sure cabal isn't confused by any other "cabal.project"
+    -- file in a parent directory
```
Comment (chshersh) [inline src/Policeman/Hie.hs:26]: Just adding a link to the comment for future context
```suggestion
    -- file in a parent directory
    -- See discussion: https://github.com/kowainik/policeman/issues/52
```

**Review by chshersh — APPROVED** [review]
Looks great! 👍🏻
